
spring:
  elasticsearch:
    rest:
      uris: ["http://cdh1:9200"]
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
  resources:
    static-locations: classpath:static/
  datasource:
    url: jdbc:mysql://localhost:3306/search?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "000000"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      resolve-lazily: false

mybatis:
  check-config-location: true
  mapper-locations: classpath:mappers/*Mapper.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 8081